# 使用yaml做配置项

db:
  mysql:
    dbname: "das_go"
    password: "root1234"
    username: "root"
    port: 3306
    host: "127.0.0.1"

log:
  # 默认路径是运行程序的目录
#  logDirector: ./logging
  logAutoFile: das.middleware
  logInfoFile: das.manual